site_name: Awesome Platform Engineering Tools
site_description: A curated list of platform solutions, tools, practices and resources for Platform Engineering.
site_author: Saif(eddine) RAJHI
repo_name: "seifrajhi/awesome-platform-engineering-tools"
repo_url: "https://github.com/seifrajhi/awesome-platform-engineering-tools"
docs_dir: "content"
theme:
  name: material
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
  features:
    - tabs
    - navigation.tabs
    - content.code.copy
    - header.autohide
    - navigation.footer
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: switch to light mode
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - attr_list
  - md_in_html

nav:
  - "Awesome Platform Engineering Tools": "index.md"
  - "Platform engineering and Cloud blogs": "https://seifrajhi.github.io/"
  
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/seifrajhi
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/rajhisaifeddine
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/rajhi-saif/
